services:
  terraform:
    image: ghcr.io/d3b-center/terraform:1.1.9
    volumes:
      - ./:/usr/local/src
      - $HOME/.aws:/root/.aws
    environment:
      - AWS_PROFILE=${AWS_PROFILE:-chopd3bprod}
      - GIT_COMMIT=${GIT_COMMIT:-latest}
      - IMAGE_DEID_ETL_DEBUG=1
      - IMAGE_DEID_ETL_SETTINGS_BUCKET=${IMAGE_DEID_ETL_SETTINGS_BUCKET:-image-deid-etl-staging-config-us-east-1}
    working_dir: /usr/local/src
    entrypoint: bash
